## Numpy array and basics
learn about chai aur code

In [3]:
import numpy as np

In [4]:
arr_id=np.array([1,2,3,4,5])
print("1D array:",arr_id)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2Darray:",arr_2d)

1D array: [1 2 3 4 5]
2Darray: [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [5]:
pylist=[1,2,3]
print("python list multiplication", pylist*2)

np_array=np.array([1,2,3]) #element wise multiplication
print("numpy array multiplication", np_array*2)


import time 
start=time.time()
py_list=[i*2 for i in range(1000000)]

print("\n List operation time:", time.time()-start)
start=time.time()
np_array=np.arange(1000000)*2
print("\n List operation time:", time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]

 List operation time: 0.048795461654663086

 List operation time: 0.00205230712890625


creating array from scratch


In [6]:
zeroes=np.zeros((3,4))
print("zeroes array--\n",zeroes)

ones=np.ones((2,3))
print("ones array--\n",ones)

full = np.full((2,2),7)
print("full array--\n",full)

two=np.full((3,4),7) #when you use full function you can create any array with any value
print("full array:\n",two)

random=np.random.random((2,3)) # random means 0,1 thats type of value
print("random array:\n",random)

sequence = np.arange(0,10,2)
print("sequence array:\n",sequence)# print 0-10 space 2

zeroes array--
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array--
 [[1. 1. 1.]
 [1. 1. 1.]]
full array--
 [[7 7]
 [7 7]]
full array:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array:
 [[0.27909986 0.63181965 0.44096199]
 [0.28699158 0.49007387 0.3376383 ]]
sequence array:
 [0 2 4 6 8]


### Vector,Matrix and Tensor

In [ ]:
vector=np.array([1,2,3])
print("vector:\n", vector)


matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: \n",matrix)

tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])# when up 2D matrix then you call tensor means 3D matrix
print("Tensor:\n", tensor)

vector:
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Propertyes


In [11]:
arr=np.array([[1,2,3],[4,5,9]])# if any element like 6.8 then the array is float

print("shape of array:", arr.shape) # shape means how many rows and columns in the array
print("dimension of array:", arr.ndim) # dimension means how many dimension in the array
print("size of array:", arr.size) # size means how many elements in the array
print("data type of array:", arr.dtype) # data type means which type of data in the array

shape of array: (2, 3)
dimension of array: 2
size of array: 6
data type of array: int64


### Array Reshaping


In [18]:
arr=np.arange(12) # arange means create an array with a range of values
print("arange array:", arr)
reshaped = arr.reshape((3,4)) # reshape means change the shape of the array
print("\nreshaped array:\n", reshaped)


flattened = reshaped.flatten() # flatten means convert the 2D array into 1D array
print("\nflattened array:\n", flattened)


#ravel(return view , instaned of copy)
raveled=reshaped.ravel() # ravel means convert the 2D array into 1D array
print("\nraveled array:\n", raveled)


# Transpose
transpose=reshaped.T # transpose means change the rows into columns and columns into rows
print("transpose array:\n", transpose)

arange array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
