In [34]:
import numpy as np

Advance operation with Business examples

In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ==== ")
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for 1st 3 resturent: ", sales_data[:3])
print("\n Sample data for 1st 3 resturent: ", sales_data[:,1:])

==== Zomato sales analysis ==== 

 Sales data shape (5, 5)

 Sample data for 1st 3 resturent:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 Sample data for 1st 3 resturent:  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [36]:
## total sale

print(np.sum(sales_data,axis=0))

yearly_total=np.sum(sales_data[:,1:],axis=0)
print("\n Yearly total sales: ", yearly_total)

## Minimum sales per resturent
min_sales=np.min(sales_data[:,1:],axis=1)
print("\n Minimum sales per resturent:", min_sales)



[     15  810000  945000 1085000 1240000]

 Yearly total sales:  [ 810000  945000 1085000 1240000]

 Minimum sales per resturent: [150000 120000 200000 180000 160000]


## practice

In [37]:
#max seale per years

max_sales=np.max(sales_data[:,1:],axis=1)
print("\n Maximum sales per year:", max_sales)

## Average sales per resturent

avg_sales=np.mean(sales_data[:,1:],axis=1) ## top to bottom axis=0,left to right axis=1
print("\n Average sales per resturent:", avg_sales)


cumsum=np.cumsum(sales_data[:,1:],axis=1)
print("\n Cumulative sum of sales per resturent:", cumsum)



 Maximum sales per year: [250000 190000 300000 270000 230000]

 Average sales per resturent: [200000. 152500. 247500. 225000. 195000.]

 Cumulative sum of sales per resturent: [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]
