In [1]:
import numpy as np

## Price Calculation

In [4]:
prices=[100,200,300]
final_price=[]
discount=10
for price in prices:
    final_price.append(price - (price * discount / 100))

print("final_price: ",final_price)


final_price:  [90.0, 180.0, 270.0]


## using Numpy

In [6]:
prices=np.array([100000,200000,3000000])
discount=10
final_price=prices-(prices*discount/100)
print(final_price)

[  90000.  180000. 2700000.]


## using matrix

In [ ]:
array=np.array([[1,2,3,4],
                [5,6,7,8]])

vector=np.array([1,2,3,4])

add=array+vector

print(add)

[[ 2  4  6  8]
 [ 6  8 10 12]]


## Multiplication


In [9]:
array=np.array([[1,2,3,4],
                [5,6,7,8]])

vector=np.array([1,2,3,4])

add=array*vector

print(add)

[[ 1  4  9 16]
 [ 5 12 21 32]]


## dot product


In [11]:
array=np.array([[1,2,3,4],
                [5,6,7,8]])

vector=np.array([1,2,3,4])

add = np.dot(array, vector)

print(add)

[30 70]


## cross product

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the cross product
cross_product = np.cross(a, b)

print("Cross product:", cross_product)

Cross product: [-3  6 -3]
