### Numpy Array opearations

In [2]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing",arr[2:7])
print("with step",arr[2:8:2]) # start:stop:step
print("nagetive indexing",arr[-3])# iterate in backward direction

Basic slicing [3 4 5 6 7]
with step [3 5 7]
nagetive indexing 8


In [15]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specify element",arr_2d[1,2]) # 2nd row and 3rd column
print("Entire row: ",arr_2d[1])# 2nd row
print("Entire column: ",arr_2d[:,1])# 2nd column targeting all rows

specify element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


Sorting

In [11]:
unsorted =np.array([3,1,4,1,5,9,2,6])
print("sorted array",np.sort(unsorted)) # sort the array


arr_2d=np.array([[3,44,2],[77,22,6],[2,65,7]])
print("sorte the : \n",np.sort(arr_2d)) # sort the array
print("sorted array by collumn \n",np.sort(arr_2d,axis=0)) # sort the array by column
print("sort the array by row: \n",np.sort(arr_2d,axis=1)) # sort the array by row

sorted array [1 1 2 3 4 5 6 9]
sorte the : 
 [[ 2  3 44]
 [ 6 22 77]
 [ 2  7 65]]
sorted array by collumn 
 [[ 2 22  2]
 [ 3 44  6]
 [77 65  7]]
sort the array by row: 
 [[ 2  3 44]
 [ 6 22 77]
 [ 2  7 65]]


## Filter

In [12]:
number=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=number[number%2==0] # filter the even number
print("even number: ",even_number)

even number:  [ 2  4  6  8 10]


### Filter with mask

In [13]:
mask = number>5
print("Number greter than 5:",number[mask]) # filter the number greater than 5


Number greter than 5: [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [19]:
indices=[0,2,4]
print(number[indices]) # filter the number by index
where_result=np.where(number>5)
print("where result: ",where_result) # store only array element
print("where result: ",number[where_result]) # filter the number greater than 5

[1 3 5]
where result:  (array([5, 6, 7, 8, 9]),)
where result:  [ 6  7  8  9 10]


In [25]:
condition_array = np.where(number > 5,"true","False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'true' 'true' 'true' 'true'
 'true']


# sumary of upper code


In [ ]:
if(number>5){
    number*4
}
else{
    number
}

SyntaxError: expected ':' (832844870.py, line 1)

Adding and removing data

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combine=np.concatenate((arr1,arr2))
print("add of two array: ",combine)


## removing



add of two array:  [1 2 3 4 5 6]


Array Compatibilty

In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("Compatibility shape",a.shape==b.shape) ##Reshaping an array changes its structure (e.g., rows and columns) without altering its data, ensuring the total elements remain the same.

Compatibility shape True


In [ ]:
original = np.array([[1,2,3],[4,5,6],[7,8,9]])
new_row=np.array([5,6,7])  # Ensure the new row has the same number of elements as the columns in 'original'

with_new_row=np.vstack((original,new_row))
print("original array: \n",original) # original array
print("Add new row: \n",with_new_row) # add new row

new_col=np.array([[7],[8],[9]])  # Ensure the new column has the same number of rows as 'original'
with_new_col=np.hstack((original,new_col))
print("with new colum: \n",with_new_col) # add new column


original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Add new row: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 6 7]]
with new colum: 
 [[1 2 3 7]
 [4 5 6 8]
 [7 8 9 9]]


Delete Array

In [13]:
arr=np.array([1,2,3,4,5])
delete=np.delete(arr,2) # delete the element at index 2
print("delete the element: ",delete) # delete the element at index 2

delete the element:  [1 2 4 5]
